name: test

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: Python
        run: |
          sudo apt-get install python3
          sudo bash "$GITHUB_WORKSPACE"/build.sh $GITHUB_WORKSPACE

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            generated_image.png
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Saving install logs
        uses: actions/upload-artifact@v2
        with:
          name: InstallLogs_${{ github.job }}
          path: |
            bootstrapper*
            installer*
          retention-days: 7
