name: test

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Maximize build disk space
        uses: easimon/maximize-build-space@v10
        with:
          swap-size-mb: 8192
      - name: Python
        run: |
          python "$GITHUB_WORKSPACE"/-m pip install -r requirements.txt

      - name: Run helper.py
        run: python helper.py

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            generated_image.png
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Saving install logs
        uses: actions/upload-artifact@v2
        with:
          name: InstallLogs_${{ github.job }}
          path: |
            bootstrapper*
            installer*
          retention-days: 7
